
GRANT INSERT, CREATE, RELOAD, REFERENCES, INDEX, ALTER ON *.* TO 'create'@'localhohostst' IDENTIFIED BY 'UYQsjBRIv6dCVfEz';
GRANT INSERT, CREATE, DROP, REFERENCES, ALTER ON *.* TO 'demo'@'localhost' IDENTIFIED BY 'YLot6pyQCwgTjolF';
GRANT SELECT ON *.* TO 'select'@'localhost' IDENTIFIED BY 'gon3rJGgpCBwksi0';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP ON *.* TO 'user'@'localhost' IDENTIFIED BY '0Z8AHyYDKN0hUYik';