<div id="container_<?=$id?>">
    <label for="<?=$id?>"><?=$label?></label>
    <span id="arrow-previous_<?=$id?>" class="arrow lnr lnr-chevron-left dtleft"></span>
    <input id="<?=$id?>" type="text" class="datepicker">
    <span id="arrow-next_<?=$id?>" class="arrow lnr lnr-chevron-right dtright"></span>
</div>
<script>
    new Datepicker('<?=$id?>')
</script>
<style>
    #<?=$id?>{
        text-align: center;
    }
    .Do{
        color: red;
    }
    #container_<?=$id?>{
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .arrow{
        cursor: pointer; 
        position: relative; 
    }
    .arrow:hover{
        transform: var(--effect-transform-hover);
    }
    .qs-datepicker{
        font-family: inherit;
    }
    .dtleft{
        left: 2rem;
    }
    .dtright{
        right: 2rem;
    }
</style>