<div id="<?=$id?>" class="row col-sm-12 col-md-12">

<select
        class = "<?=$class?>"
        <?=$printName?>
        <?=$printTitle?>
        <?=$required?>
        <?=$onfocus?>
        <?=$onblur?>
        <?=$onclick?>
        <?=$readonly?>
        <?=$for?>
        <?=$required?> 
        <?=$value?> 
        <?=$list?>
        <?=$disabled?>
        <?=$tabindex?>
        <?=$onchange?>
    > 
        <option value="" hidden></option>
        <?php if($options):?>
            <?php foreach($options as $key => $val): ?>
                <option value="<?=$key?>"  <?php if($key == $selected) echo "selected"?>><?=$val?></option>
            <?php endforeach ?>
        <?php endif?>
    </select> 
    <label for="<?=$idElement?>"><?=$label?></label>
</div> 
<script>
    class Select extends Component{
        constructor(id){
            super()
            this.el = document.getElementById(id).getElementsByTagName('select')[0]
            this.o =  this.el.getElementsByTagName('option')
            this.CLASS_SELECTED = 'valid'
        }
        addOption(value, option){
            let line = document.createElement('option')
                line.value = value 
                line.innerHTML = option
            this.el.append(line)
        }
        default(){
            this.el.value = 0
        }
        clear(){
            let ops = this.el.querySelector('option:not(:first-child)')
            for(let i in ops){
                if(ops[i]) this.el.remove(ops[i].selectedIndex)
            }
        }
        reset(){

            this.el.classList.remove(this.CLASS_SELECTED)
            
            let options = this.el.getElementsByTagName('option')

            for (let option of options) {
                option.selected = false 
            }
        }
        value(v){
            if(v != undefined){
                this.el.value = v
                this.el.seletedIndex = v
            }
            return  this.el.value
        }
        
        option(data){
            let options = this.el.getElementsByTagName('option'),
                optionselected = false

            for (let option of options) {
                if(option.getAttribute('value') == data) {
                    option.selected = true 
                    optionselected = true
                } else option.selected = false 
            }

            if(optionselected && data != 0 ) this.el.classList.add(this.CLASS_SELECTED)
            else this.el.classList.remove(this.CLASS_SELECTED)
        }
    }
</script>