<?php $id = $data['id']??randomid('input')?>

<div class="row" id="<?=$data['id']??randomid('input')?>">
    <div class="col-sm-12 col-md-12">
        <input 
            type="text" 
            id="<?='input_'.$id?>"
            class="collapse" 
            placeholder="<?=ucfirst($data['placeholder']??'')?>" 
            name="<?=$data['name']?>" 
            <?=isset($data['require'])?'required':''?> 
            <?=isset($data['minlength'])?"minlength=${data['maxlength']}":''?>
            <?=isset($data['maxlength'])?"maxlength=${data['maxlength']}":''?>
            <?=isset($data['pattern'])?"pattern='${data['pattern']}'":''?>
            <?=isset($data['tittle'])?"tittle='${data['tittle']}'":''?>
            :valid />
        <label for="username"><?=ucfirst($data['lavel']??$data['name'])?></label>
    </div>
</div>