<!DOCTYPE html>
<html lang="es">

<body id="--id">
    <m-select options="['uno','dos']"/>
    <m-accordion id="--id_1" class="1">
        <h1>Accordion</h1>
    </m-accordion>


    <style lang="less" scoped>
        #--id_3 {
            display: inline-block;
            background: blue;
            height: 50px;
        }

        .red {
            background: red;
        }
    </style>
</body>

</html>