<!DOCTYPE html>
<html lang="es">

<body id="--id">
    <m-btn-success/>
    <m-accordion id="--id_1" class="cuadrado" value="">
        <m-input class="red"/>
        <m-accordion id="--id_1_1" class="cuadrado" value="">
            <h3>TERCER</h3>
        </m-accordion>
    </m-accordion>
    <m-accordion id="--id_2" class="cuadrado" value="">
        <h2>Segundo TAG</h2>
    </m-accordion> 
    <m-input />


    <style lang="less" scoped>
        #--id_3 {
            display: inline-block;
            background: blue;
            height: 50px;
        }

        .red {
            background: red;
        }

        .cuadrado {
            border: 1px solid;
        }
    </style>
</body>

</html>