<header id="bartools">
    <div id="bartools-actions">
        <m-icon  id='--id_add' class="menu-buttons" style="color:red" icon='plus-circle' onclick='app.sections.add()' label='Nuevo'/>
        <m-icon  id='--id_del' class="menu-buttons" icon='cross-circle' onclick='menu.del()' label='Eliminar'/>
        <m-icon  id='--id_prev' class="menu-buttons" icon='chevron-left-circle' onclick='app.sections.prev()' label='Anterior'/>
        <m-icon  id='--id_next' class="menu-buttons" icon='chevron-right-circle' onclick='app.sections.next()' label='Siguiente'/>
        <m-icon  id='--id_print' class="menu-buttons" icon='printer' onclick='app.sections.print()' label='Imprimir'/>
        <m-icon  id='--id_conf' class="menu-buttons" icon='cog' onclick='app.sections.conf()' label='Configurar'/>
        <m-icon  id='--id_filter' class="menu-buttons" icon='funnel' onclick='app.sections.filter()' label='Filter'/>

        <div id="search" onblur="menu.search.close()">
            <m-icon  id='--id_search' class="menu-buttons" icon='magnifier' onclick='menu.search.toggle()' label='Buscar'/>
            <m-input id='--id_txtSearch' placeholder='Escribe tu búsqueda' onkeyup = 'menu.search.keypress(event)' tabindex = '-1' title = 'Pulse Enter para realizar la búsqueda.'/>
        </div>
    </div>
    <div id="bartools-central"> 
    </div>  
    <div id="bartools-general">
        <m-icon  id='--id_help' class="menu-buttons" icon='question-circle' onclick='app.help()' label='Acerca de'/>
        <m-icon icon="book" href="https://nestorpons.github.io/TPVON/manual/" label="Manual de usuario" target="_blank"/>
        <m-icon icon="power-switch" label="Salir" onclick="app.close()"/>
    </div>
</header>
<style>
    #bartools{
        background-color: var(--main-color);
        color: var(--nav-font-color);
        padding: 0 20px 0 60px;
        display: grid;
        grid-template-columns: auto 1fr auto;
        align-items: center;
        overflow-x: visible;
        overflow-y: visible;
        height: auto;
    
    }
    #bartools i:active{
        color: var(--nav-link-color);
    }
    #bartools a, #bartools a:hover, #bartools a:link, #bartools a:visited{
        color: inherit;
    }
    #bartools a:hover{
        font-weight: bold;
    }   
    #bartools > div{
        flex-grow: 1;
        display: flex;
        align-items: inherit;
    }
    #bartools > div:nth-child(2){
        text-align: center;
    }
    #bartools > div:last-child{
        justify-content: flex-end;
    }
    #bartools .lnr{
        display: inline-block;
        font-size: 1.4rem;
        cursor: pointer;
        margin: 2px 5px;
    }
    #bartools .lnr:hover{
        font-weight: bold;
    }
    #bartools #--id_txtSearch{
        position: relative;
        top: 0;
        left: 3204px;
        height: 58px;
        z-index: 1;
        text-align: left;
        display: flex; 
        align-items: center;  
        width: 300px;
        background-color: var(--form-back-color);
        margin-left: 5px ;
    }
    #bartools #--id_txtSearch>input{
        position: absolute;
        width: 97%;
    }
    #bartools #search{
        display: inherit; 
        align-items: center;
    }
    #bartools #search .row{
        background: transparent;
    }
    #bartools #search .row input, ::placeholder{
        color: inherit;
    }
    #bartools #search .row ::placeholder{
        color: #aaa;
    }
</style>
<script>
    var menu = {
        tile    : document.getElementById('bartools-name-sections'),
        buttons : {
            $add        : $('#--id_add'),
            $del        : $('#--id_del'),
            $next       : $('#--id_next'),
            $prev       : $('#--id_prev'),
            $search     : $('#--id_search'),
            $print      : $('#--id_print'),
            $conf       : $('#--id_conf'),
            $filter     : $('#--id_filter'),
            show(arr = []){               
                $('#bartools').find('#bartools-actions').find('.menu-buttons').hide()
                for(i in arr){
                    menu.buttons['$'+arr[i]].show()
                }
            }
         },
        search  : {
            $search     : $('#--id_txtSearch'), 
            $txtSearch  : $('#--id_txtSearch').find('input'),
            $label      : $('#--id_search').find('.label'), 
            $icon       : $('#--id_search'),
            velocity    : 500,
            isOpen      : false,
            open(){
                this.$txtSearch.val('');
                this.$label.text('Cerrar');
                
                this.$icon
                    .removeClass('lnr-magnifier')
                    .addClass('lnr-cross')

                this.$search.animate({
                    left:  0
                }, this.velocity, fn => {
                    this.$txtSearch.focus()
                })
                this.isOpen = true;
                return this;
            },
            close(){
                this.$label.text('Buscar');
                // Icono buscar
                this.$icon
                    .removeClass('lnr-cross')
                    .addClass('lnr-magnifier');

                // Cerrar inputtext
                this.$search.animate({
                    left: window.innerWidth + 1000
                }, this.velocity)
                this.isOpen = false;
                return this;     
            },
            toggle(){
                event.stopPropagation();
                if( this.isOpen ) this.close()
                else this.open();
                return this;
            },
            keypress(e){
                if(e.key == 'Enter') this.search();
            },
            search(){
                typeof app[app.sections.active].search == 'function' && app[app.sections.active].search(this.$txtSearch.val()); 
                return this;
            },
            placerholder(param = null){
                if(param) $txtSearch.attr('placeholder', param);
                return $txtSearch.attr('placeholder');
            }
         },
        del(){
            if(app.mens.confirm('¿Desea eliminar el registro?'))
                app.sections.del()
         }
    }
</script>