<section id="appadmin">
    @include(\FOLDERS\VIEWS . 'admin/barTools.phtml')
    @include(\FOLDERS\VIEWS . 'admin/navBar.phtml')
    @include(\FOLDERS\VIEWS . 'admin/main.phtml')

    <style lang="less" scoped>
        display: grid;
        grid-template-areas: 
        'header header'
        'menu main'
        'menu footer';
        grid-template-rows: 60px 1fr 60px;
        grid-template-columns: auto 1fr;

        header {
            grid-area: header;
        }

        main {
            grid-area: main;
            height: 82vh;
        }

        nav {
            grid-area: menu;
        }

        footer {
            grid-area: footer;
        }
    </style>
    <script>
        'use strict'
        DB.set('servicios', $$jsonServices);
        DB.set('usuarios', $$jsonUsers);
        DB.set('empresa', $$data_company);
        DB.set('promos', $$promos);
        DB.set('config', $$config);
        DB.set('familias', $$families);
        DB.set('impagos', $$debts);

        app.clock();

        // Guardamos el session storage el token de autentificación
        sessionStorage.setItem('jwt', '$$jwt');
    </script>

</section>