site_name: Documentación TPVOn
repo_url: https://github.com/nestorPons/TPVON/
site_description: "Una aplicación para terminales de punto de software libre."
site_author: Néstor Pons
nav:
  - Inicio: 'index.md'
  - Manual de usuario: 'manual.md'
  - Información técnica: 'technical.md'
  - Acerca de: 'about.md'
  - Versionado: 'version.md'
  - Licencia: 'license.md'
theme:
    name: material
    logo:
        icon: school
    favicon: img/favicon.ico
    language: es
    palette:
        primary: teal
        accent: orange
extra:
  social:
    - type: 'github'
      link: 'https://github.com/nestorpons'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
