<button 
        type = "--type" id="--idElement"  class="--class collapse --mainclass" placeholder=" "
        style = "--style" name = "--name" tile = "--tile"
        value = "--value" tabindex = "--tabindex" 
        onfocus = "--onfocus" onblur = "--onblur" onclick = "--onclick"
        onkeypress = "--onkeypress" onkeydown = "--onkeydown" onkeyup = "--onkeyup"
        onchange = "--onchange" --require --disabled --readonly --checked  
    >
    @if (--spinner) <i class="spinner hidden"></i> @endif
    @if (--icon) <i class="lnr lnr---icon"></i> @endif
    <span class="caption">--caption</span>
</button>