<m-input id="--id" class="--row --hidden" >  
    <input 
        id ="input--id"
        type = "--type" 
        class="--class" placeholder=" "
        style = "--style" name = "--name" tile = "--tile"
        @if (--pattern) pattern = "--pattern" @endif
        @if (--for) for = "--for" @endif 
        @if (--maxlength) maxlength = "--maxlength" @endif
        @if (--minlength) minlength = "--minlength" @endif
        value = "--value" list = "--list" tabindex = "--tabindex" 
        onfocus = "--onfocus" onblur = "--onblur" onclick = "--onclick"
        onkeypress = "--onkeypress" onkeydown = "--onkeydown" onkeyup = "--onkeyup"
        onchange = "--onchange" --require --disabled --readonly --checked  
    />
    <label for="icon--id" class="--classLabel">--label</label>
    @if (--icon) <i id="icon--id" class="lnr lnr---icon"></i> @endif
</m-input>
