<div class="<?=$row??''?> <?=$hidden??''?>" id="<?=$id?>">

        <input 
            type = "<?=$type?>" 
            id = "<?=$idElement?>"
            class = "<?=$class?>"
            placeholder=" "
            style = "<?=$style??''?>"
            <?=$placeholder?>
            <?=$name?>
            <?=$title?>
            <?=$minlength?>
            <?=$maxlength?>
            <?=$pattern?>
            <?=$for?>
            <?=$required?> 
            <?=$value?> 
            <?=$list?>
            <?=$disabled?>
            <?=$tabindex?>
            <?=$onfocus?>
            <?=$onblur?>
            <?=$onclick?>
            <?=$onkeypress?>
            <?=$onkeydown?>
            <?=$onkeyup?>
            <?=$onchange?>
            <?=$onload?>
            <?=$readonly?>
            <?=$checked?>
            <?=@$attr_default?>
        />
        <label for="<?=$idElement?>" class="<?=$classLabel?>"><?=$label?></label>
        <?php if($iconlast):?>
            <i id="<?=$id?>" class="lnr lnr-<?=$icon?>"></i>
        <?php endif?>

</div>