<component id="--id" class="row col-sm-12 col-md-12">
    <ul>
        <?php foreach ($arrABC as $l) : ?>
            <li onclick="--id.sel(window.event)" value=<?= $l ?>><?= $l ?></li>
        <?php endforeach ?>
    </ul>
    <style scoped>
        ul {
            width: 100%;
            display: flex;
            justify-content: space-evenly;
        }

        ul li {
            display: inline;
            padding-left: 3px;
            padding-right: 3px;
            cursor: pointer;
            border: 1px solid var(--a-link-color);
            border-radius: var(--universal-border-radius);
            padding: var(--universal-padding)
        }

        ul li:hover {
            color: var(--blockquote-color);
            transform: scale(1.1)
        }
    </style>
    <script>
        const --id = {
            sel(el) {
                const
                val = el.path[0].attributes.value.value.toLowerCase(),
                table = <?= $table ?>, 
                body = table.getElementsByTagName('tbody')[0],
                tr = body.getElementsByTagName('tr'), 
                find = table.getElementsByClassName(`${val}`);

                for(const el of tr){
                    el.classList.add('hidden');
                }
                for(const el of find){
                    el.classList.remove('hidden');
                }
                
            }
        }
    </script>
</component>