<component id="--id" class="menu-square">
    <label for="--id" class="active"> <?= $tile ?></label>
    <content class="">
        <?= $content ?>
        <i class="lnr lnr-cross-circle icon-close"></i>
    </content>
    <style lang="less">
        .menu-square {
            /* transition: display 2s linear; */
            transition: all 1.5s ease 0.5s;

            label {
                align-items: center;
                justify-content: center;
                cursor: pointer;
                height: 200px;
                width: 200px;

                border: 1px solid var(--main-color);
                color: var(--main-color);
                border-radius: var(--universal-border-radius);
            }

            content {
                i {
                    position: relative;
                    top: 21px;
                    right: 10px;
                    font-size: 1.2rem;
                }
            }

            label,
            content {
                display: none;
            }

            .active {
                display: inline-flex !important;
            }
        }
    </style>
    <script scoped>
        let el = document.getElementById('--id'),
            ic = el.querySelector('.icon-close'),
            cnt = el.querySelector('content'),
            lbl = el.querySelector('label')

        el.onclick = e => {
            e.stopPropagation()
            lbl.classList.remove('active')
            cnt.classList.add('active')
        }
        ic.onclick = e => {
            e.stopPropagation()
            cnt.classList.remove('active')
            lbl.classList.add('active')
        }
    </script>
</component>