<m-modal>
  <!--Sistema de activacion/cierre de la ventana -->
  <input type="checkbox" id="control_--id" class="modal">
  <div>
    <div class="card card-modal" id="card--id">
      <!-- icono de cierre de ventana -->
      <label for="control_--id" class="lnr lnr-cross-circle icon-close"></label>
      <!--Titulo de la ventana -->
      <h1 id="tileModal--id" class="tile"></h1>
      <!--Cuerpo de la ventana -->
      <?php include($body) ?>
    </div>
  </div>
  <style lang="less" scoped>
    .icon-close {
      position: absolute;
      right: -22px;
      font-size: 1.5rem;
      top: -17px;
      background: transparent;
      z-index: 1000;
      &::before{
        content: "\e880";
        background: radial-gradient(var(--back-color), transparent);
        border-radius: 50%;
      }
      @media(max-width: 375px){
        top: 0; 
        right: 0; 
      }
    }

    h1 {
      text-align: center;
    }
  </style>
  <script>
    class Modal {
      constructor(id) {
        this.el = document.getElementById(id).querySelector(`.card`);
        this.$el = $('#' + id).find('.card')
        this.$switch = $('#control_' + id)
        this.$el.keyup(e => (e.key === 'Escape') && this.close())
        // Variable de estado del formulario: nuevo, editanto
        this.attrState = false
        this.data = [];
      }
      clear() {
        this.el.getElementsByTagName('form')[0].reset()
        return this
      }
      setTile(tile) {
        this.el.getElementsByClassName('tile')[0].innerHTML = tile
        return this
      }
      open(data = null) {
        if (data) this.load(data)
        this.$switch.prop('checked', true)
        let o = this.el.querySelector('[tabindex="1"]')
        o != null && o.focus()
        return this
      }
      close() {
        this.$switch.prop('checked', false)
        return this
      }
      load(data) {
        const inputs = this.$el.find('input'),
          selects = this.$el.find('select'),
          d = exist(data.id) ? data : data[0]

        // Cargamos la informacion en una variable para poder consultar
        this.data = d

        selects.each(function() {
          if (d.id != -1)
            $(this)
            .find('[selected]').attr('selected', false).end()
            .find('option[value="' + d[$(this).attr('name')] + '"]').attr('selected', true)
          else
            $(this)
            .find('[default]').attr('selected', true)
        })
        inputs.each(function() {
          if ($(this).attr('type') == 'checkbox' || $(this).attr('type') == 'radio') {
            // Si es nuevo ponemos el estado por defecto pasandolo en el parametro data
            if (d[$(this).attr('name')] == $(this).val()) $(this).prop('checked', true)
            else $(this).prop('checked', false)

          } else $(this).val(d[$(this).attr('name')])

        })
        return this
      }
      async getData(rsp) {
        const r = await app.formToObject(this.el);
        return {
          r,
          ...rsp
        };
      }
      state(value) {
        if (value) {
          this.attrState = value
          const el = this.el.querySelector(`[name="id"]`)

          if (el) {
            if (value == 'new') el.parentElement.classList.add('hidden')
            else el.parentElement.classList.remove('hidden')
          }

          return this
        } else {
          return this.attrState
        }
      }
    }
  </script>
  <m-modal>