<div class="row <?=$hidden?>" id="<?=$id?>">
    <div class="col-sm-12 col-md-12">
        <input 
            type = "<?=$type?>" 
            id = "<?=$idElement?>"
            placeholder = ' '
            class = "<?=$class?>"
            
            <?=$name?>
            <?=$title?>
            <?=$minlength?>
            <?=$maxlength?>
            <?=$pattern?>
            <?=$for?>
            <?=$required?> 
            <?=$value?> 
            <?=$list?>
            <?=$disabled?>
            <?=$tabindex?>
            <?=$onfocus?>
            <?=$onblur?>
            <?=$onclick?>
            <?=$onload?>
            <?=$readonly?>
        />
        <label for="<?=$id?>"><?=$label?></label>
    </div>
</div>