<div class="row <?=$hidden?>" id="<?=$id?>">
    <div class="col-sm-12 col-md-12">
        <input 
            type = "<?=$type?>" 
            id = "<?=$idSel?>"
            placeholder = ' '
            class = "<?=$class?>"
            
            <?=$name?>
            <?=$title?>
            <?=$minlength?>
            <?=$maxlength?>
            <?=$pattern?>
            <?=$for?>
            <?=$required?> 
            <?=$value?> 
            <?=$list?>
            <?=$disabled?>
            <?=$tabindex?>
        />
        <label for="<?=$idSel?>"><?=$label?></label>
    </div>
</div>