<div class="row" id="<?=$id?>">
    <div class="col-sm-12 col-md-12">
        <input 
            type = "<?=$TYPE?>" 
            id = "<?=$idSel?>"
            placeholder = ' '
            class = "<?=$class?>"
            
            <?=$name?>
            <?=$title?>
            <?=$minlength?>
            <?=$maxlength?>
            <?=$pattern?>
            <?=$for?>
            <?=$required?> 
        />
        <label for="<?=$idSel?>"><?=$label?></label>
    </div>
</div>