<!-- <label for="control_<?=$id?>"></label> -->
<input type="checkbox" id="control_<?=$id?>" class="modal">
<div>
  <div class="card card-modal" id="<?=$idElement?>">
    <label for="control_<?=$id?>" class="modal-close" ></label>
    <?php include($body)?>
  </div>
</div>
  <style>
  #<?=$idElement?>{
      overflow: inherit;
      padding: 2rem;
  }
  #<?=$idElement?>  .modal-close{
    top: -1em;
    background-color: inherit;
    right: -1em;
    border-radius: 25px;
    padding: 0;
    border: 1px solid var(--border-color);

  }
  #<?=$idElement?> label.modal-close:hover:before{
    color: var(--input-invalid-color) ;
  }
  </style>
  <script>
  class Modal{
    constructor(id){
      this.$form = $('#<?=$prefix_element?>'+ id)
      this.$switch = $('#control_' + id)
    }
    show(){
      this.$switch.prop('checked',true)
    }
    hide(){
      this.$switch.prop('checked',false)
    }
  }
  </script>