<div id="<?=$id?>" class="row col-sm-12 col-md-12">
    <select 
        id="<?=$idElement?>" 
        class = "<?=$class?>"
        <?=$printName?>
        <?=$printTitle?>
        <?=$required?>
        <?=$onfocus?>
        <?=$onblur?>
        <?=$onclick?>
        <?=$readonly?>
        <?=$for?>
        <?=$required?> 
        <?=$value?> 
        <?=$list?>
        <?=$disabled?>
        <?=$tabindex?>
    > 
        <option value="" hidden></option>
        <?php foreach($options as $key => $val): ?>
            <option value="<?=$key?>" <?= ($key == $selected) ? "selected default" : ''; ?>><?=$val?></option>
        <?php endforeach ?>
    </select> 
    <label for="<?=$idElement?>"><?=$label?></label>
</div>  