
<table id="<?= $idElement ?>" class="<?= $class ?>">
    <thead>
        <?php foreach ($columns as $key => $val) : ?>
            <th class="<?= $val ?>"><?= $val ?></th>
        <?php endforeach ?>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    </tfoot>
</table>
<template id="template_<?= $id ?>">
    <tr <?= $onclick ?>>
        <?php foreach ($columns as $key => $val) : ?>
            <td class="<?= $val ?>"></td>
        <?php endforeach ?>
    </tr>
</template>

