<?php namespace app\views\components\controllers;?>
<header id="bartools">
    <div>
        <?php $add = new Icon('plus-circle', ['onclick'=>'app.sections.add()'])?>
        <?php $del = new Icon('cross-circle', ['onclick'=>'app.sections.del()'])?>
        <?php $prev = new Icon('chevron-left-circle', ['onclick'=>'app.sections.prev()'])?>
        <?php $next = new Icon('chevron-right-circle', ['onclick'=>'app.sections.next()'])?>
    </div>
    <div>
        <?php new DatePicker?>
    </div>  
    <div>
        <?php new ButtonCloseApp?>
    </div>
</header>
<style>
    #bartools{
        background-color: var(--main-color);
        color: var(--nav-font-color);
        padding: 0 20px 0 60px;
        display: flex;
        align-items: center;
        overflow-x: visible;
        overflow-y: visible;
        height: auto;
    
    }
    #bartools a, #bartools a:hover, #bartools a:link, #bartools a:visited{
        color: var(--nav-font-color);
    }
    #bartools div{
        flex-grow: 1;
    }
    #bartools div:nth-child(2){
        text-align: center;
    }
    #bartools div:last-child{
        text-align: right;
    }

    #bartools .lnr{
        display: inline-block;
        font-size: 1.4rem;
        cursor: pointer; 
    }
    #bartools .lnr:hover{
        transform: var(--effect-transform-hover);
    }
</style>
<script>
    const menu = {
        buttons : {
            $next: $('#<?= $next->id()?>'),
            $prev: $('#<?= $prev->id()?>'),
            $add: $('#<?= $add->id()?>'),
            $del: $('#<?= $del->id()?>'),
            show(arr = []){               
                $('#bartools').find('.menu-buttons').hide()
                for(i in arr){
                    menu.buttons['$'+arr[i]].show()
                }
            }
        }
    }
</script>