<?php namespace app\views\components\controllers;?>
<header id="bartools">
    <div>
        zona herramienta
    </div>
    <div>
        <?php new DatePicker?>
    </div>  
    <div>
        <?php new ButtonCloseApp?>
    </div>
</header>
<style>
    #bartools{
        background-color: var(--main-color);
        color: var(--nav-font-color);
        padding: 0 20px 0 60px;
        display: flex;
        align-items: center;
        overflow-x: visible;
        overflow-y: visible;
        height: auto;
    
    }
    #bartools a, #bartools a:hover, #bartools a:link, #bartools a:visited{
        color: var(--nav-font-color);
    }
    #bartools div{
        flex-grow: 1;
    }
    #bartools div:nth-child(2){
        text-align: center;
    }
    #bartools div:last-child{
        text-align: right;
    }

    #bartools .lnr{
        display: inline-block;
        font-size: 1.4rem;
        cursor: pointer; 
    }
    #bartools .lnr:hover{
        transform: var(--effect-transform-hover);
    }
</style>