<?php 
namespace app\views\components\controllers;
?>
<section id="appadmin">
    <?php include(\FOLDERS\VIEWS . 'admin/barTools.phtml')?>
    <?php include(\FOLDERS\VIEWS . 'admin/navBar.phtml')?>
    <?php include(\FOLDERS\VIEWS . 'admin/main.phtml')?>
    <?php include(\FOLDERS\VIEWS . 'admin/footer.phtml')?>
</section>
<style lang="less">
    #appadmin{ 
        display: grid;
        grid-template-areas:
            'header header'
            'menu main'
            'menu footer';
        grid-template-rows: 60px 1fr 60px;
        grid-template-columns: auto 1fr; 
        header{
            grid-area: header;
        }    
        main{
            grid-area: main;
            height: 82vh;
        }
        nav{
            grid-area: menu;
        }
        footer{
            grid-area: footer;
        }
    }
</style>
<script>
    'use strict'
    DB.set('servicios', <?=$jsonServices?>)      
    DB.set('usuarios', <?=$jsonUsers?>)
    DB.set('empresa', <?=$data_company?>)

    app.clock()

</script>

