<?php 
namespace app\views\components\controllers;
?>
<section id="appadmin">
    <?php include(\FOLDERS\VIEWS . 'admin/barTools.phtml')?>
    <?php include(\FOLDERS\VIEWS . 'admin/navBar.phtml')?>
    <?php include(\FOLDERS\VIEWS . 'admin/main.phtml')?>
    <?php include(\FOLDERS\VIEWS . 'admin/footer.phtml')?>
</section>
<style>
    #appadmin{
        display: grid;
        grid-template-areas:
            'header header'
            'menu main'
            'menu footer';
        grid-template-rows: 60px 1fr 60px;
        grid-template-columns: auto 1fr; 
    }
    #appadmin header{
        grid-area: header;
    }    
    #appadmin main{
        grid-area: main;
    }
    #appadmin nav{
        grid-area: menu;
    }
    #appadmin footer{
        grid-area: footer;
    }
</style>
<script>
    app.db.put('servicios', <?=$Services->toJSON()?>)
    app.db.put('usuarios', <?=$Users->toJSON()?>)

    //Art.put()
       

    app.data.services = <?=$Services->toJSON()?>;
    app.data.users = <?=$Users->toJSON()?>;
    app.data.config = <?=$Config->toJSON()?>;
    app.data.config = app.data.config[1]
    app.clock()
    </script>

