CREATE TABLE `emails` (
  `id` int(22) UNSIGNED AUTO_INCREMENT NOT NULL  PRIMARY KEY,
  `id_empresa` INT(11) NOT NULL REFERENCES `empresas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  `email` varchar(50) NOT NULL UNIQUE KEY
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_spanish2_ci;