<section id="control">
    <?php
    $txt01 = new InputText(['label' => 'Ticket']);
    $txt02 = new InputText(['label' => 'Cliente']); 
    $table = new Table(['columns'=>['id_linea', 'Nombre', 'Descripcion', 'fecha'], 
            'class'=>'hoverable', 'ondblclick'=>'control.addDate(event.target)']);
    ?>
</section>
<style lang="less">
    #control{
        display: grid;
        grid-template-columns: 1fr 1fr; 
        
        table{
            grid-column: 1 / span 2;
        }
        .fecha{
            text-align: center;
        }
        .lnr{
            cursor      : pointer; 
            text-align  : center;
            margin      : auto; 
            &:hover{
                border-radius   : 25px;
            }
            &.lnr-cross-circle{
                color   : red;
                &:hover{
                    background-color: red; 
                    color           : white;    
                }
            }
            &.lnr-plus-circle{
                color   : green; 
                &:hover{
                    background-color: green; 
                    color           : white;    
                }
            }
        }
    }
</style>
<script>
var control = {
    table       : 'control',
    buttons     : ['prev', 'next', 'search'], 
    db          : new Db('control'), 
    Table       : new Table('<?=$table->idEl()?>'),
    txtTicket   : <?=$txt01->idEl()?>,
    txtCli      : <?=$txt02->idEl()?>,
    btnDel      : ' <span class="lnr lnr-cross-circle" onclick="control.delDate(event.target)"></span>',
    btnAdd      : ' <span class="lnr lnr-plus-circle" onclick="control.addDate(event.target)"></span>',
    load(){
        app.post({
            controller  : this.table,
            action      : 'get'     ,
            data        : {}
        }, data => {
            this.db.set(data)
            .then(_=>this.db.last())
            .then(lst => {
                this.loadTable(lst)
            })
        })
    },
    add(data){
        this.db.lastId()
        .then(id => this.db.add(data, 'id', id + 1 ))
    },
    next(){
        this.loadTable(this.db.next())
    },
    prev(){
        this.loadTable(this.db.prev())
    },
    loadTable(data){
        if(data == undefined) return false
        this.Table.clear()

        this.txtTicket.value = data.id

        users.db.get('id', data.id_cliente)
        .then(d => d[0])
        .then(({nombre}) => this.txtCli.value = nombre)

        for(let i in data.lines){
            let line = data.lines[i]
            services.db.get('id', line.articulo)
            .then(d => d[0])
            .then(ser => {
                let date = (line.fecha_regalo != null) ? app.date.format(line.fecha_regalo, 'datetime') + this.btnDel : this.btnAdd

                this.Table.addLine(
                    line.id, 
                    [line.id, ser.nombre, ser.descripcion, date ]
                )
            })
        }
    },
    search(value){
        if(!isNaN(value)) {
            this.db.get('id', value)
            .then(d => d[0])
            .then(d => {
                if( d != undefined) this.loadTable(d)
                else app.mens.error('No se ha podido encontrar el registro')
            }) 
        }
        else {
            echo('AKI:: Funcion no definida')
        } 
    },
    addDate(e){
        let $el = $(e),
            $parent = $el.parents('tr'), 
            id = $parent.attr('idline'),
            date = app.date.format(app.date.now(), 'datetime' )

        app.post({
                controller  : 'control', 
                action      : 'addDate',
                data        : {
                    id_linea    : id,
                    fecha       : date
                }
            }
            , (d, s) => {
                $el.parents('tr').find('.fecha').html(date + this.btnDel)
            }
        )          
    },
    delDate(e){
        let $el = $(e),
            $parent = $el.parents('tr'), 
            id = $parent.attr('idline')
        app.post({
                controller  : 'control',
                action      : 'delete',
                data        : {
                    id_linea    : id
                }
            }
            , (d, s) => {
            if(s) $el.parent().html(this.btnAdd)
        })        
    },
}
</script>
