<section id="promos">
    <form controller="promos" action="save" class="input-group">
        <fieldset>
            <legend>Promociones</legend>
            <?php
            $txt00 = new InputRead(['label' => 'Id', 'name'=>'id']);
            $txt01 = new InputText(['label' => 'Nombre', 'name'=>'nombre','tabindex'=>1, 'title'=>"Introduzca el nombre de la promoción", 'required'=>true]);
            $txt02 = new InputText(['label' => 'Numero de dias', 'name'=>'valor']);
            $txt03 = new InputText(['label' => 'DTO% a aplicar', 'name'=>'dto']);
            ?> 
        </fieldset>
    </form>
</section>
<script> 
var promos = {
    table   : 'promos',
    el      : document.getElementById('promos'),
    form    : document.getElementById('promos').getElementsByTagName('form')[0],
    buttons : [],
    change  : false,
    load(){
        let d = DB.get('promos')[0]
        app.loadDataToForm(d, this.form)
    },
    onblur(callback){
        this.change && this.save()
        typeof callback == 'function' && callback()
    },
    save(){
        app.post({
                controller: 'promos',
                action: 'save',
                data: app.formToObject(this.form)
            })
        DB.set(this.table, app.formToObject(this.form), 'id' , 1)   
    },
}
</script>
