<?php namespace app\views\components\controllers;?>
<component id="buttonsTicket">
    <?php $btnPrTicket = new ButtonSuccess(['onclick'=>'ticket.print()', 'caption'=>'Imprimir'])?>
    <?php $btnSndTicket = new ButtonSuccess(['onclick'=>'ticket.send()', 'caption'=>'Enviar'])?>
</component>
<component id="ticket" class="hidden">
    <img src="<?=$Data->pathLogo?>" alt="Logotipo">
    <div class="data">
        <div>TICKET DE VENTA <span><?=$Data->nombre()?></span></div>
        <div>Dir: <?=$Data->calle?> <?=$Data->numero?></div>
        <div><?=$Data->CP?> <?=$Data->poblacion?></div>
        <div>Tel: <?=$Data->telefono?> NIF: <?=$Data->nif?></div>
        <br>
        <div>N Fac: <span id="idTicket"></span></div>
        <div>Fecha: <span id="dateTicket"></span></div>
    </div>
        <?php
            $tblTicket = new Table(['columns'=>['Cant', 'Des', 'Imp']]);
        ?>
    <p>
        <div>Iva incluído</div>
        <div>¡GRACIAS POR SU VISITA!</div>
    </p>
</component>
<style id='ticketStyle'>
    #ticket {
        transform: scale(0.8);
        text-align: center;
        overflow: auto;
    }
    #buttonsTicket{
        margin: 1rem 0;
    }
    #ticket .data{
        margin: 5px auto; 
    }
    #ticket img{
        max-width: 200px;
    }
    #<?=$tblTicket->id()?>{
        padding: 5px;
    }
    #ticket .footer td{
        font-weight: bold;
        font-size: 1.2rem;
    }
    @media print{
        *{
            page-break-after:avoid;
            text-align: center;
        }
        component{
            margin: none;
        }
        button{
            display: none !important;
        }
        img{
            max-width: 60mm;
        }
        @page{
            /* AKI:: En tintero cambiar el tamaño del papel del ticket*/
            size: 80mm 190mm;
        }
        table thead{
            text-decoration: underline;
            border-bottom: 1px solid black;
        }
        table td:first{
            border-top: 1px solid black;
        }
        table td:last{
            text-align: right;
        }
        .break {
            page-break-after: always;
        }
        table .footer td{
            font-weight: bold;
            font-size: 1.2rem;
        }
    }
</style>
<script>
    const ticket = {
        Ticket: null, 
        table : {
            id: '<?=$tblTicket->id()?>',
            ob: $('#<?=$tblTicket->id()?>')
        }, 
        print(){
            this.save(false)
            /* 
            var printContents = document.getElementById('ticket').innerHTML;
            printContents += '<style>' + document.getElementById('ticketStyle').innerHTML + '</style>'
            w = window.open();
            w.document.write(printContents);
            w.document.close(); // necessary for IE >= 10
            w.focus(); // necessary for IE >= 10
            w.print();
            w.close();
            return true; */ 
        },
        open(Ticket){
            this.Ticket = Ticket
            const $template = $($('#template_' + this.table.id)[0].innerHTML)
            $('#ticket')
                .find('#dateTicket').text(Ticket.date.toLocaleString()).end()
                .find('#idTicket').text(Ticket.id).end()
            for(i in Ticket.lines){
                let line =  Ticket.lines[i]
                let l = $template.clone()
                        .find('.Cant').text(line.qua).end()
                        .find('.Des').text(line.des).end()
                        .find('.Imp').text(line.amo).end()
                
                this.table.ob.find('tbody').append(l) 
            }   
            let t = $template.clone()
                .addClass('footer')
                .find('.Cant').text('').end()
                .find('.Des').text('TOTAL').end()
                .find('.Imp').text(Ticket.total()).end()
            this.table.ob.find('tbody').append(t) 
        },
        save(sendMail = false){
            let Ticket = this.Ticket
            Ticket.fecha = Ticket.fecha.toLocaleString()
            let data = {
                controller: 'tickets',
                action: 'new', 
                data: JSON.stringify(Ticket)
            }
            app.post(data, function(){
                echo('YATA')
            })
        }
    }
</script>