<?php namespace app\views\components\controllers;?>
<section id="users">
    <?php
    $table = new Table(['columns'=>['id', 'Nombre', 'Tel', 'Email'], 
        'class'=>'hoverable', 'onclick'=>'users.show(window.event)']);
    $editUser = new Modal(['body'=> \VIEWS\ADMIN\SECTIONS . 'users/new.phtml'], false);
    ?>

</section>
<script>
'use strict'
var users = {
    buttons: ['add', 'del', 'search'],
    Table: new Table('<?=$table->idEl()?>'),
    Form : new Modal('<?=$editUser->id()?>'),
    edit(){
        
    },
    load(){
        let users  = app.data.get('usuarios')
        for( i in users ){
            var user = users[i]
            this.Table.addLine(
                user.id, 
                [user.id, user.nombre, user.tel, user.email]
            )
        }
    },
    show(e){
        this.Form.show()
    }
}
</script>
<style>
    #users #<?=$table->id()?>{
        max-height: 80vh ;
    }
</style>