<?php namespace app\views\components\controllers;?>
<section id="users">
    <?php
    $table = new Table(['columns'=>['id', 'Nombre', 'Tel', 'Email'], 
        'class'=>'hoverable', 'onclick'=>'users.show(window.event)']);
    $editUser = new Modal(['body'=> \VIEWS\ADMIN\SECTIONS . 'users/edit.phtml'], false);
    ?>

</section>
<script>
'use strict'
var users = {
    table: 'usuarios',
    buttons: ['add', 'del', 'search'],
    currentId: null, 
    Table: new Table('<?=$table->idEl()?>'),
    Form : new Modal('<?=$editUser->id()?>'),
    validation(){
        let data = this.Form.getData(),
            usuarios = app.data.get('usuarios')

        for(i in usuarios) {
            let u = usuarios[i]
            if(u.dni == data.dni && u.id != data.id) return {success: false, code: 'dni', mens: 'Error dni duplicado'} 
            else if( u.email == data.email && u.id != data.id ) return {success: false, code: 'email', mens: 'Error email duplicado'} 
        }

        return {success: true}
    },
    del(){
        this.Table.delLine(this.currentId)
        this.Form.hide()
    },
    add(){
        let data = {    
            id: -1,
            estado: 1
        }
        this.Form.clear().show(data).setTile('Nuevo usuario')
    },
    save(data){ 
        app.data.set(this.table, data , 'id', data.id)

        if (this.currentId == -1 ) this.Table.addLine(data.id, [data.id, data.nombre, data.tel, data.email])
        else this.Table.updateLine(data.id, [data.id, data.nombre, data.tel, data.email])

        this.Form.hide()
    },
    load(){
        let users  = app.data.get(this.table)
        for( i in users ){
            var user = users[i]
            // Listamos los usuarios activos solamente
            if(user.estado == 1){
                this.Table.addLine(
                    user.id, 
                    [user.id, user.nombre, user.tel, user.email]
                )
            }
        }
    },
    show(e){
        this.currentId = e.path[1].attributes.idline.value
        let data = app.data.get(this.table, 'id', this.currentId)
        this.Form.show(data).setTile('Edicion usuario')
    }
}
</script>
<style>
    #users #<?=$table->id()?>{
        max-height: 80vh ;
    }
</style>