<section id="loginrememberpassword">
    <div>
        <form controller="login" action="reset">
            <fieldset class="container">
                <legend>Recordar Contraseña</legend>
                <m-input-text label="Email del usuario" name="email" required="false"/>
                
            </fieldset>
            <m-btn-success/>
        </form>
        <m-a href="login">Regresar a login</m-a>
    </div>
    <style>
        #loginrememberpassword {
            margin: auto;
            margin: auto;
            display: inline-flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 80%;
        }

        #loginrememberpassword>div {
            width: 4 20px;
        }
    </style>
</section>