<section id="login">
    <div>
        <form controller="login" action="auth">
            <h1 translate="no">$$nombre</h1>
            <fieldset class="container">
                <legend>Login</legend>
                <m-input type="email" label="Email del usuario" name="email" required="true" />
                <m-input type="password" label="Contraseña" name="password" required="true" />
            </fieldset>
            <m-btn-success />
        </form>
        <m-a href="loginrememberpassword" class="float-right">Recordar contraseña</m-a>
    </div>
    <style lang="less" scoped>
        margin: auto;
        display: inline-flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        height: 80%;
    </style>
</section>