<section id="resetpassword" style="
    width: 420px; 
">
    <form controller="login" action="activatePassword">
        <h1>$$name_company</h1>
        <fieldset  class="container">
            <legend>Restaurar contraseña</legend>
            <m-input type="hidden" name="id" value="$$idUSer"/>
            <m-input type="password" name="password" label="Introduzca una contraseña" required="true"/>
            <m-input type="password" label="Repita la contraseña" required="true"/>
        </fieldset>
        <m-btn-success/>
    </form>
</section>