
<section id="login" style="width: 420px;">
    <form controller="login" action="auth">
        <h1><?= $nombre?></h1>
        <fieldset class="container">
            <legend>Login</legend>
            <?php
            new InputText([
                'type'=>'email', 
                'label' => 'Email del usuario', 
                'name' => 'email', 
                'required' => true]);
            new InputPass(['label' => 'Contraseña', 'name' => 'password', 'required' => true])
            ?>
        </fieldset>
        <?php new ButtonSuccess(['caption' => 'Acceder']); /* new ButtonCancel */ ?>
    </form>
    <a href="loginnewuser">Nuevo usuario</a>
    <a href="loginrememberpassword" class="float-right">Recordar contraseña</a>
</section>
<style>
    #login {
        margin: auto;
    }
</style>