<section id="loginnewuser" style="
    width: 420px; 
">
    <form controller="login" action="newuser">
        <h1><?=$Company->nombre()?></h1>
        <fieldset  class="container">
            <legend>Registro nuevo usuario</legend>
            <?php 
                new InputText(['label'=>'Nombre y apellidos', 'name'=>'nombre', 'class'=>'toverify', 'required'=>false]);

                $mail = new InputText(['label'=>'Email del usuario', 'name'=>'email', 'required'=>false]);
                new InputText(['label'=>'Repetir email', 'class'=>'verify', 'for'=>$mail->id(), 'required'=>false]);

                $pass = new InputPass(['label'=>'Contraseña', 'name'=>'password', 'class'=>'toverify', 'required'=>true]);
                new InputPass(['label'=>'Repetir contraseña', 'class'=>'verify', 'for'=> $pass->id(), 'required'=>true]);
            ?>
        </fieldset>
        <?php new ButtonSuccess; new ButtonCancel?>
    </form>
    <m-a href="login">Regresar a login</m-a>
</section>
<style scoped>
    #loginnewuser{
        margin: auto;
    }
</style>