<section id="login" style="width: 420px;">
    <form controller="login" action="auth">
        <h1 translate="no"><?= $nombre?></h1>
        <fieldset class="container">
            <legend>Login</legend> 
            <m-input type="email" label="Email del usuario" name="email" required="true"/>
            <m-input type="password" label="Contraseña" name="password" required="true"/>
        </fieldset>
        <?php new ButtonSuccess(['caption' => 'Acceder']); /* new ButtonCancel */ ?>
    </form>
    <m-a href="loginrememberpassword" class="float-right">Recordar contraseña</m-a>
</section>
<style>
    #login {
        margin: auto;
    }
</style>