<component id="--id">
    <button type="button" id="--id_el" class="$$class collapse" placeholder=" " name="$$name" tile="$$tile" value="$$value" tabindex="$$tabindex" onfocus="$$onfocus" onblur="$$onblur" onclick="$$onclick" onkeypress="$$onkeypress" onkeydown="$$onkeydown" onkeyup="$$onkeyup" onchange="$$onchange" $$require $$disabled $$readonly $$checked>
        @if ($$spinner) <i class="spinner hidden"></i> @endif
        @if ($$icon) <i class="lnr lnr-$$icon"></i> @endif

        @if ($$caption) <span class="caption">$$caption</span> @endif
    </button>
    <style>
        #--id button:disabled{
            color: grey !important;
            border-color: grey !important;
        }
    </style>
    <script>
        class MyButton extends MyComponent {
            constructor (id) {
                super(id); 
                this.el = this.cont.getElementsByTagName('button')[0]; 
                this.cap = this.el.getElementsByClassName('caption')[0]; 
            }
            caption(value){
                if (value != undefined) this.cap.innerText = value ; 
                return this.cap.innerText;
            }
            on(){
                this.el.removeAttribute('disabled');
                return this; 
            }
            off(){
                this.el.setAttribute('disabled', true); 
                return this;
            }
        }
    </script>
</component>