<component id="--id"> 
    <button type = "submit" id="--id_el"  class="$$class collapse tertiary" placeholder=" "
            name = "$$name" tile = "$$tile"
            value = "$$value" tabindex = "$$tabindex" onfocus = "$$onfocus" onblur = "$$onblur" onclick = "$$onclick"
            onkeypress = "$$onkeypress" onkeydown = "$$onkeydown" onkeyup = "$$onkeyup"
            onchange = "$$onchange" $$require $$disabled $$readonly $$checked  
        >
        @if ($$spinner) <i class="spinner hidden"></i> @endif
        @if ($$icon) <i class="lnr lnr-$$icon"></i> @endif
        <span class="caption">Aceptar</span>
    </button>
</component>