<component id="--id">
    <button type="button" id="--id_el" class="$$class collapse" placeholder=" " name="$$name" tile="$$tile" value="$$value" tabindex="$$tabindex" onfocus="$$onfocus" onblur="$$onblur" onclick="$$onclick" onkeypress="$$onkeypress" onkeydown="$$onkeydown" onkeyup="$$onkeyup" onchange="$$onchange" $$require $$disabled $$readonly $$checked>
        @if ($$spinner) <i class="spinner hidden"></i> @endif
        @if ($$icon) <i class="lnr lnr-$$icon"></i> @endif

        @if ($$caption) <span class="caption">$$caption</span> @endif
    </button>
    <script>
        class MyButton extends MyComponent {
            constructor (id) {
                super(id); 
                this.el = this.cont.getElementsByTagName('button')[0]; 
            }
        }
    </script>
</component>