<component id="--id" class="$$hidden" >  
    <input 
        id ="--id_input"
        type = "checkbox" 
        class="$$class" placeholder="$$placeholder"
        style = "$$style" name = "$$name" tile = "$$tile"
        @if ($$pattern) pattern = "$$pattern" @endif
        @if ($$for) for = "$$for" @endif 
        @if ($$maxlength) maxlength = "$$maxlength" @endif
        @if ($$minlength) minlength = "$$minlength" @endif
        default = "$$default" value = "$$value" 
        list = "$$list" tabindex = "$$tabindex" 
        onfocus = "$$onfocus" onblur = "$$onblur" onclick="$$onclick"
        onkeypress = "$$onkeypress" onkeydown = "$$onkeydown" onkeyup = "$$onkeyup"
        onchange = "$$onchange" $$required $$disabled $$readonly $$checked  
    />
    <label for="--id_input" class="$$classLabel">$$label</label>
    @if ($$icon) <i id="icon$$id" class="lnr lnr$$-icon"></i> @endif
    <style scoped>
        display: flex; 
        align-items: center;
        label {
            z-index: 101;
        }
    </style>
    <script>
        class MyCheckbox{
            constructor(id){
                this.id = id; 
                this.component = document.getElementById(id);
                this.el = this.component.getElementsByTagName('input')[0]
            }
            value(value = null){
                if (value != null) this.el.value = value ; 
                return this.el.value;
            }
            checked(value = null){
                if(value != null) this.el.checked = value
                return this.el.checked; 
            }
        }
    </script>
</component>
