<component id="--id" tabindex ="$$tabindex">
    @if($$href) <a href="$$href" target="$$target"> @endif
    <i id="--id_icon" class="lnr lnr-$$icon $$class" onclick="$$onclick" >
        <span class="label">$$label</span>
    </i>
    @if($$href) </a> @endif
    <style scoped>
        .label {
            font-size       : 0.8rem;
            vertical-align  : middle;  
        }
        /* Quitamos el borde de seleccion*/
        outline:none !important;
        outline-width: 0 !important;
        box-shadow: none;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;

    </style>
</component>

