<component id="--id" class="row $$hidden" >  
    <input 
        id ="--id_input"
        type = "text" 
        class="$$class" placeholder="$$placeholder"
        style = "$$style" name = "$$name" tile = "$$tile"
        pattern = "$$pattern"
        for = "$$for" 
        maxlength = "$$maxlength" 
        minlength = "$$minlength" 
        default = "$$default" value = "$$value" 
        list = "$$list" tabindex = "$$tabindex" 
        onfocus = "$$onfocus" onblur = "$$onblur" onclick="$$onclick"
        onkeypress = "$$onkeypress" onkeydown = "$$onkeydown" onkeyup = "$$onkeyup"
        onchange = "$$onchange" $$required $$disabled $$readonly $$checked  
    />
    <label for="--id_input" class="$$classLabel">$$label</label>
    @if ($$icon) <i id="icon$$id" class="lnr lnr-$$icon"></i> @endif
    <style lang="less" scoped>
        label {
            z-index: 101;
        }
        input[type="color"]{
            width: 10ch;
            margin-left: 13ch;
        }
    </style>
</component>
