<component id="--id" class="row $$hidden" >  
    <input 
        id ="--id_input"
        type = "text" 
        class="$$class" placeholder="$$placeholder"
        style = "$$style" name = "$$name" tile = "$$tile"
        @if ($$pattern) pattern = "$$pattern" @endif
        @if ($$for) for = "$$for" @endif 
        @if ($$maxlength) maxlength = "$$maxlength" @endif
        @if ($$minlength) minlength = "$$minlength" @endif
        default = "$$default" value = "$$value" 
        list = "$$list" tabindex = "$$tabindex" 
        onfocus = "$$onfocus" onblur = "$$onblur" onclick="$$onclick"
        onkeypress = "$$onkeypress" onkeydown = "$$onkeydown" onkeyup = "$$onkeyup"
        onchange = "$$onchange" $$required $$disabled $$readonly $$checked  
    />
    <label for="--id_input" class="$$classLabel">$$label</label>
    @if ($$icon) <i id="icon$$id" class="lnr lnr-$$icon"></i> @endif
    <style lang="less" scoped>
        label {
            z-index: 101;
        }
        input[type="color"]{
            width: 10ch;
            margin-left: 13ch;
        }
    </style>
    <script>
        class MyInputText{
            constructor(id){
                this.id = id;
                this.component = document.getElementById(id);
                this.el = this.component.getElementsByTagName('input')[0];
            }
            value(value){
                if (value != undefined) this.el.value = value ; 
                return this.el.value;
            }
            change(fn){
                this.el.addEventListener('change', fn);
                return this;
            }
        }
    </script>
</component>
