/**
* Componente MyList
* Elemento que crea una lista alfabetica y que ejecuta una acción cuando se pulsa encima de sus letras.
*
* Requerimientos : necesita de un attributo $$ref para referenciar al objeto al cual debe de realizar la acción.
*
* autor : Nestor Póns
* email : nestorpons@gmail.com
* licencia: MIT 2020
*/

<component id="--id" class="">
    <ul>
        @for(['A','B','C','D','E','F','G','H','I','J','K','L','M','N','Ñ','O','P','Q','R','S','T','U','V','W','X','Y','Z'])
        <li onclick="--id.sel(window.event)" value="$$value">$$value</li>
        @endfor
    </ul>
    <style scoped>
        ul {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
        }

        ul li {
            display: table;
            padding-left: 3px;
            padding-right: 3px;
            cursor: pointer;
            border: 1px solid var(--a-link-color);
            border-radius: var(--universal-border-radius);
            padding: var(--universal-padding);
            width: 1.2ch;
            height: 1.2ch;
            text-align: center;
            vertical-align: middle;
        }

        ul li:hover {
            color: var(--blockquote-color);
            transform: scale(1.1)
        }
    </style>
    <script>
        const --id = {
            sel(el) {
                const
                    val = el.target.attributes.value.value.toLowerCase(),
                    table = "$$ref",
                    body = table.getElementsByTagName('tbody')[0],
                    tr = body.getElementsByTagName('tr'),
                    find = table.getElementsByClassName(`${val}`);
                
                for (const el of tr) {
                    el.classList.add('hidden');
                }
                for (const el of find) {
                    el.classList.remove('hidden');
                }
            }
        }
    </script>
</component>