<component id="--id">
  <!--Sistema de activacion/cierre de la ventana -->
  <input type="checkbox" id="control_--id" class="modal" >
  <div>
    <div class="card card-modal" id="card--id">
      <!-- icono de cierre de ventana -->
      <label for="control_--id" class="lnr lnr-cross-circle icon-close"></label>
      <!--Titulo de la ventana -->
      <h1 id="tileModal--id" class="tile"></h1>
      <!--Cuerpo de la ventana -->
      --content
    </div>
  </div>
  <style lang="less" scoped>
    .icon-close {
      position: absolute;
      right: -12px;
      font-size: 26px;
      top: -13px;
      background: white;
      z-index: 1000;
      border-radius: 87%;
      width: 6px;
      height: 14px;
      text-align: center;
      vertical-align: middle;
      display: flex;
      justify-content: center;
      align-items: center;

      &::before {
        content: "\e880";
      }

      @media(max-width: 375px) {
        top: 0;
        right: 0;
      }
    }

    h1 {
      text-align: center;
    }
  </style>
  <script>
    class MyModal extends MyComponent{
      constructor(id) {
          super(id);
          this.el = this.cont.querySelector(`.card`);
          this.cont.addEventListener('keyup', e => (e.key === 'Escape') && this.close());
          this.$el = $(this.cont).find('.card');
          this.$switch =  $(this.cont).find('input:first');
          // Variable de estado del formulario: nuevo, editanto
          this.attrState = false
          this.data = [];
      }
      clear() {
        this.el.getElementsByTagName('form')[0].reset()
        return this
      }
      setTile(tile) {
        this.el.getElementsByClassName('tile')[0].innerHTML = tile
        return this
      }
      open(data = null) {
        if (data) this.load(data)
        this.$switch.prop('checked', true)
        let o = this.el.querySelector('[tabindex="1"]')
        o != null && o.focus()
        return this
      }
      close() {
        this.$switch.prop('checked', false)
        return this
      }
      load(data) {
        const inputs = this.$el.find('input'),
          selects = this.$el.find('select'),
          d = exist(data.id) ? data : data[0]

        // Cargamos la informacion en una variable para poder consultar
        this.data = d

        selects.each(function() {
          if (d.id != -1)
            $(this)
            .find('[selected]').attr('selected', false).end()
            .find('option[value="' + d[$(this).attr('name')] + '"]').attr('selected', true)
          else
            $(this)
            .find('[default]').attr('selected', true)
        })
        inputs.each(function() {
          if ($(this).attr('type') == 'checkbox' || $(this).attr('type') == 'radio') {
            // Si es nuevo ponemos el estado por defecto pasandolo en el parametro data
            if (d[$(this).attr('name')] == $(this).val()) $(this).prop('checked', true)
            else $(this).prop('checked', false)

          } else $(this).val(d[$(this).attr('name')])

        })
        return this
      }
      async getData(rsp) {
        const r = await app.formToObject(this.el);
        return {
          r,
          ...rsp
        };
      }
      state(value) {
        if (value) {
          this.attrState = value
          const el = this.el.querySelector(`[name="id"]`)

          if (el) {
            if (value == 'new') el.parentElement.classList.add('hidden')
            else el.parentElement.classList.remove('hidden')
          }

          return this
        } else {
          return this.attrState
        }
      }
    }
  </script>
</component>