sut:
  build: tests/.
  dockerfile: Dockerfile.test
  links:
    - web1804-php7
    - web1604-php7
    - web1404-php7

web1804-php7:
  build: .
  dockerfile: ./1804/Dockerfile
  ports:
    - "3000:80"

web1604-php7:
  build: .
  dockerfile: ./1604/Dockerfile
  ports:
    - "3001:80"

web1404-php7:
  build: .
  dockerfile: ./1404/Dockerfile
  ports:
    - "3002:80"
