<?php namespace app\views\components\controllers;?>
<section id="login" style="
    width: 420px; 
">
    <form controller="login" action="auth">
        <h1><?=$Company->nombre()?></h1>
        <fieldset  class="container">
            <legend>Login</legend>
            <?php 
                new InputText(['label'=>'Email del usuario', 'name'=>'email', 'required'=>false, 'value'=>'nestorpons@gmail.com']);
                new InputPass(['label'=>'Contraseña', 'name'=>'password', 'required'=>true, 'value'=>'123123'])
            ?>
        </fieldset>
        <?php new ButtonSuccess; new ButtonCancel?>
    </form>
    <a href="loginnewuser">Nuevo usuario</a>
    <a href="loginrememberpassword" class="float-right">Recordar contraseña</a>
</section>
<script src="/js/login.min.js"></script>