<section id="resetpassword" style="
    width: 420px; 
">
    <form controller="login" action="activatePassword">
        <h1><?=$Company->nombre()?></h1>
        <fieldset  class="container">
            <legend>Restaurar contraseña</legend>
            <?php 
                new InputHidden(['name'=>'id', 'value' => $data->idUser]);
                new InputPass(['name'=>'password', 'label'=>'Introduzca una contraseña', 'required'=>true]);
                new InputPass(['label'=>'Repita la contraseña', 'required'=>true]);
            ?>
        </fieldset>
        <?php new ButtonSuccess?>
    </form>
</section>