<? $o = ($Data['admin'])
    ? [0 => 'Cliente', 1 => 'Usuario', 2 => 'Administrador']
    : [0 => 'Cliente', 1 => 'Usuario'];
?>
<component class="editUser">
    <form controller="user" action="save" validation="app.users.validation(callback)" callback="app.users.save(data)">
        <fieldset>
            <legend></legend>
            <m-input type="text" label="nombre" tabindex="1" name="nombre" required="true" />
            <m-select label="Tipo de usuario" tabindex="2" name="nivel" class="valid" required="true" options="<?= $o ?>" selected="0" option_default="false" />
  
            <div class="collapse">
                <input type="checkbox" id="editUser_main" aria-hidden="true">
                <label for="editUser_main" aria-hidden="true" class="collapse">
                    Datos usuario
                </label>
                    
                <div>
                    <m-input type="text" label="Id usuario" tabindex="3" name="id" readonly="true" />
                    <m-input type="text" label="Código" tabindex="5" name="codigo"/>
                    <m-input type="tel" label="Teléfono" tabindex="6" name="tel"/>
                    <m-input type="text" label="DNI" tabindex="7" name="dni" pattern="(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))" tile="Introduzca el dni"/>
                    <m-input type="text" label="Fecha nacimiento dd/mm/yyyy" tabindex="8" name="fecha_nacimiento" pattern="(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}" />
                    <m-input type="text" label="Observaciones" tabindex="9" name="obs"/>    
                </div>
                <input type="checkbox" id="editUser_second" aria-hidden="true">
                <label for="editUser_second" aria-hidden="true" class="collapse">
                    Datos cuenta
                </label>
                <div>
                    <m-checkbox label="Bloquear cuenta" tabindex="10" name="estado" default="1" value="2"/>
                    <m-checkbox label="Aplicar promociones" tabindex="11" name="promos" value="1"/>
                    <m-checkbox label="Enviar emails" tabindex="12" name="emails" value="1"/>
                </div>
            </div>
        </fieldset>
        <m-input type="hidden" name="noAuth" value="1" />
        <m-btn-success caption="Guardar" tabindex="11"/>
        <m-btn-cancel caption="Eliminar" tabindex="12" class="fnDelete"/> 

    </form>
</component>
<style lang="less">
    .editUser {
        form {
            min-width: auto;
            padding: 0;
            border: none;

            m-input {
                display: block;
            }
        }

        .collapse>:checked+label+div {
            max-height: inherit;
        }
    }
</style>