<component class="editUser">
    <form controller="user" action="save" validation="app.users.validation(callback)" callback="app.users.save(data)">
        <fieldset>
            <legend>Datos usuario</legend>
            <?php
                $id = new InputRead(['label' => 'Id usuario', 'name'=>'id']);
                $name = new InputText(['label' => 'Nombre','tabindex'=>1, 'name'=>'nombre', 'required'=>true]);
                $email = new InputText(['label' => 'Email','tabindex'=>2, 'name'=>'email']);
                $phone = new InputText(['label' => 'Teléfono','tabindex'=>3, 'name'=>'tel']);
                $dni = new InputText(['label' => 'DNI','tabindex'=>4, 'name'=>'dni', 'pattern'=>"(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))", 'title'=>"Introduzca el dni" ],  false);
                $fnaci = new InputText(['label' =>'Fecha nacimiento dd/mm/yyyy','tabindex'=>5, 'name'=>'fecha_nacimiento', 
                'pattern' => '(0[1-9]|1[0-9]|2[0-9]|3[01])/(0[1-9]|1[012])/[0-9]{4}']);
                $level = new Select(['label' => 'Tipo usuario', 'tabindex'=>6, 'name'=>'nivel', 'class'=>'valid',
                'options' => [0=>'Cliente', 1=>'Usuario', 2=>'Administrador'],'selected' => 0, 'required'=>true]);
                
                $status = new Checkbox(['label' => 'Bloquear cuenta', 'tabindex'=>7, 'name'=>'estado', 'default'=>'1', 'value'=>2]);
                $promos = new Checkbox(['label' => 'Activar promociones', 'tabindex'=>8, 'name'=>'promos', 'default'=>'0', 'value'=>1]);

                $hidden = new InputHidden(['name'=>'noAuth', 'value'=>'1']);
                $btnSave = new ButtonSuccess(['caption'=>'Guardar', 'tabindex'=>8]);
                $btnDel = new ButtonCancel(['caption'=>'Eliminar', 'tabindex'=>9, 'class'=>'fnDelete']);
            ?> 
        </fieldset>
    </form>
</component>
<style>
    .editUser form{
        min-width: 325px;
    }
</style> 