<section id="--id">
    <form controller="company" action="save" class="input-group">
        <fieldset>
            <legend>Datos empresa</legend>
            <m-input type="hidden" name="id" value="1"/>
            <m-input-text tabindex="1" label="Nombre empresa" name="nombre" title="Introduzca el nombre de la empresa" required="true"/>
            <m-input-text tabindex="2" label="Teléfono" name="telefono"/> 
            <m-input-text tabindex="3" label="Email" name="email"/> 
            <m-input-text tabindex="4" label="Calle" name="calle"/> 
            <m-input-text tabindex="5" label="Numero" name="numero"/> 
            <m-input-text tabindex="6" label="Escalera" name="escalera"/> 
            <m-input-text tabindex="7" label="Piso" name="piso"/> 
            <m-input-text tabindex="8" label="Población" name="poblacion"/> 
            <m-input-text tabindex="9" label="Provincia" name="provincia"/> 
            <m-input-text tabindex="10" label="Codigo postal" name="CP" title="Introduzca el codigo postal"/> 
            <m-select-countries tabindex="11" name="pais"/>
        </fieldset>
    </form>

    <form controller="config" action="save" class="input-group">
        <fieldset>
            <legend>Datos aplicación</legend>
            <m-input type="hidden" name="id" value="1"/>
            <m-input-text tabindex="12" label="% Iva aplicado" name="iva"/> 
            <m-input-text tabindex="13" label="Dias cheque regalo" name="dias"/> 
        </fieldset>
    </form>
    <form controller="" action="" class="input-group">
        <fieldset>
            <legend>Gerente</legend>
            <m-select id="--id_sel1" label="Gerente" required="true" tabindex="14"/>
        </fieldset>
    </form>

    <form controller="promos" action="save" class="input-group">
        <fieldset>
            <legend>Promocion fidelización</legend>
            <m-input-text tabindex="15" label="Nombre" name="nombre" title="Introduzca el nombre de la promoción"/>
            <m-input-text tabindex="16" label="Total dias" name="valor"/>
            <m-input-text tabindex="16" label="DTO% a aplicar" name="dto"/>
        </fieldset>
    </form>
</section>
<style lang="less">
    #--id {
        display: grid;
        grid-template-columns: minmax(300px, 1fr) minmax(300px, 1fr) minmax(300px, 1fr);
        grid-template-rows: 1fr 1fr 1fr;

        @media(max-width: 650px) {
            grid-template-columns: 1fr 1fr;
        }

        &>* {
            height: min-content;
            border: none;
            padding: 0;

            &:first-of-type {
                grid-row-start: 1;
                grid-row-end: -1;
            }
        }

    }
</style>
<script>
    // Cargamos los datos de la base de datos 
    app.conf = {
        name : 'Configuración',
        buttons: [],
        id_user: null,
        selUsers : new Select('--id_sel1'), 
        form: {
            company: document.getElementById('--id').getElementsByTagName('form')[0],
            conf: document.getElementById('--id').getElementsByTagName('form')[1],
            user: document.getElementById('--id').getElementsByTagName('form')[2],
            promos: document.getElementById('--id').getElementsByTagName('form')[3],
        },
        table: {
            company: 'empresa',
            conf: 'config',
            users: 'usuarios',
        },
        async load() {
            // Cargamos los datos promociones
            DB.get('promos')
                .then(d => d[0])
                .then(d => app.loadDataToForm(d, this.form.promos))

            DB.get('empresa')
                .then(e => e[0])
                .then(e => {
                    DB.get('usuarios', 'nivel', 2, 'estado==1' )
                    .then(async d => {
                        // Eliminamos la opcion en blanco (SIEMPRE tiene  que tener un gerente)
                        this.selUsers.required()
                        // Cargamos los datos en el select 
                        for (let u of d) this.selUsers.addOption(u.id, u.nombre);

                        const n = e.id_gerente; 
                        this.selUsers.value(n);
                        // Cargamos los datos
                        this.id_user = d.id;
                    })
                    app.loadDataToForm(e, this.form.company)
                })
            DB.get('config')
                .then(d => d[0])
                .then(d => {
                    app.loadDataToForm(d, this.form.conf)
                })
            this.form.user
        },
        exit(callback) {
            this.save()
        },
        save() {
            // Guardamos empresa
            const datacompany = {
                ...app.formToObject(this.form.company),
                id_gerente : this.selUsers.value()
            }            
            // Envio de datos
            app.post({
                controller: 'company',
                action: 'save',
                data: datacompany
            }, (r, s) => {
                if(s)
                    DB.set(this.table.company, datacompany, 'id', 1)
                else 
                    app.notify.error('No se pudieron guardar los datos!!')
            })

            // Guardamos datos aplicación
            DB.set(this.table.conf, app.formToObject(this.form.conf), 'id', 1)
            $(this.form.conf).submit()


            // Guardamos promociones
            DB.post('promos', 'save', {
                ...app.formToObject(this.form.promos),
                id: 1
            })
        },
    }
</script>