<section id="control">
    <m-input-text id="--id_txt1" label="ticket" reandonly="true"/>
    <m-input-text id="--id_txt2" label="Cliente" reandonly="true"/>
    <m-input-text id="--id_txt3" label="Fecha" reandonly="true"/>
    <m-input-text id="--id_txt4" label="Vencimiento" onchange="app.control.savedate(window.event.target)"/>
    <m-table id="--id_table1" columns="['id_linea', 'Nombre', 'Descripcion', 'fecha']" class="hoverable"/>

    <style lang="less" scoped>
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr;

        #--id_table1 {
            grid-row: 2;
            grid-column-start: 1;
            grid-column-end: -1;
        }

        .fecha {
            text-align: center;
        }

        .lnr {
            cursor: pointer;
            text-align: center;
            margin: auto;

            &:hover {
                border-radius: 25px;
            }

            &.lnr-cross-circle {
                color: red;

                &:hover {
                    background-color: red;
                    color: white;
                }
            }

            &.lnr-plus-circle {
                color: green;

                &:hover {
                    background-color: green;
                    color: white;
                }
            }
        }
    </style>
    <script>
        app.control = {
            name : 'Vales regalo',
            table: 'present',
            buttons: ['prev', 'next', 'search', 'print', 'conf'],
            data: null,
            Table: new MyTable('--id_table1'),
            txtTicket: --id_txt1.querySelector('input'),
            txtCli: --id_txt2.querySelector('input'),
            txtFecha: --id_txt3.querySelector('input'),
            txtFechaV: --id_txt4.querySelector('input'),
            btnDel: ' <span class="lnr lnr-cross-circle" onclick="app.control.delDate(event)"></span>',
            btnAdd: ' <span class="lnr lnr-plus-circle" onclick="app.control.addDate(event)"></span>',
            load() {
                app.post({
                    controller: this.table,
                    action: 'get',
                    data: {}
                }, data => {
                    DB.set(this.table, data)
                        .then(_ => DB.last(this.table))
                        .then(lst => {
                            this.loadTable(lst);
                        });
                })
            },
            // Impresion de los vales regalo
            print() {
                // Comprobamos que este cargado el módulo del vale regalo
                if (app.present) {
                    let p = app.present,
                        t = this.Table,
                        elemento = p.el,
                        estilos = p.style,
                        ventana = window.open('', '', 'PRINT'),
                        arr = []

                    for (let i in t.data) {
                        arr.push(t.data[i][2])
                    }

                    p.clear()
                    //Cargamos los datos en la vista
                    p.description(arr);
                    p.date = new Date(date.format(this.txtFechaV.value, 'sql'))

                    ventana.document.write('<html><head><title>' + document.title + '</title>');
                    ventana.document.write(`<style type="text/css">${estilos.innerHTML}</style>`);
                    ventana.document.write(`</head><body id="${elemento.id}">`);
                    ventana.document.write(elemento.innerHTML);
                    ventana.document.write('</body></html>');
                    ventana.document.close();
                    ventana.focus();
                } else {
                    // Si no esta cargado lo cargamos pero no lo mostramos
                    app.get({
                        controller: 'present',
                        action: 'view',
                        data: {}
                    }, false, html => {
                        let body = document.querySelector('body');
                        let div = document.createElement('div');
                        div.innerHTML = html;
                        let component  = div.firstChild ; 
                        
                        body.appendChild(component);


                        // Cargamos la clase
                        app.present = new Present(component);
                        this.print();
                    })
                }
            },
            async next() {
                const d =  await DB.next(this.table, this.data.id); 
                this.loadTable(d); 
                return this; 
            },
            async prev() {
                const d =  await DB.prev(this.table, this.data.id); 
                this.loadTable(d); 
                return this;
            },
            // Carga los datos en la tabla y demás controles 
            loadTable(data) {

                if (data == undefined) return console.warn('NO se han mandadod datos a loadTable');
                this.Table.clear();

//AKI :: Hay que actualizar los datos de la tabla local o cambiar el sistema 

                // Cargamos los datos  en el objeto 
                this.data = data

                // Cargamos datos vista id 
                this.txtTicket.value = data.id;

                this.txtFecha.value = date.format(data.fecha, 'short')
                this.txtFechaV.value = date.format(data.fecha_vencimiento, 'short')

                DB.get('usuarios', 'id', data.id_cliente)
                    .then(d => d[0])
                    .then(({
                        nombre
                    }) => this.txtCli.value = nombre);

                for (let i in data.lines) {
                    let line = data.lines[i]
                    DB.get('servicios', 'id', line.articulo)
                        .then(d => d[0])
                        .then(ser => {

                            let d = (line.fecha != null) ? date.format(line.fecha, 'datetime') + this.btnDel : this.btnAdd

                            this.Table.addLine(
                                line.id,
                                [line.id, ser.nombre, ser.descripcion, d]
                            )
                        })
                }
            },
            search(value) {
                if (!isNaN(value)) {
                    DB.get(this.table, 'id', value)
                        .then(d => d[0])
                        .then(d => {
                            if (d != undefined) this.loadTable(d)
                            else app.mens.error('No se ha podido encontrar el registro')
                        })
                } else {
                    echo('AKI:: Funcion no definida')
                }
            },
            addDate(e) {
                const 
                    $el = $(e.target),
                    $parent = $el.parents('tr'),
                    id = $parent.attr('idline'),
                    d = date.datetime()

                app.post({
                    controller: 'present',
                    action: 'addDate',
                    data: {
                        id: id,
                        fecha: d
                    }
                }, fn => {
                    $el.parents('tr').find('.fecha').html(d + this.btnDel)
                })
            },
            delDate(e) {
                e.stopPropagation();
                echo('DEL')
                let $el = $(e.target),
                    $parent = $el.parents('tr'),
                    id = $parent.attr('idline'); 

                app.post({
                    controller: 'present',
                    action: 'delete',
                    data: {
                        id: id
                    }
                }, d => {
                    $el.parent().html(this.btnAdd)
                })
            },
            savedate(el) {
                if (el.value) {
                    app.post({
                        controller: 'present',
                        action: 'expiration',
                        data: {
                            id: this.txtTicket.value,
                            fecha_vencimiento: date.format(this.txtFechaV.value, 'sql')
                        }
                    }, d => {
                        echo('Guardado fecha ticket regalo ...')

                    })
                } else {
                    app.mens.error('Tiene que haber una caducidad!!')
                }
            },
            add(ticket){
                DB.set(this.table, {ticket})
                    .then(_ => DB.last(this.table))
                    .then(lst => {
                        echo(lst)
                        this.loadTable(lst);
                    });
            }
        }
    </script>
</section>