<component class="hidden">
    <img src="/tpv/img/fondo_regalo.jpg" alt="Cheque regalo">
    <h1>Cheque Regalo</h1>
    <p>Disfrute de los servicios de</p>
    <div id="descripcion">Tratamiento/s que se regala</div>
    <div id="mensfecha">
        Antes del
        <div id="fecha">
            <span id="dia">13</span> de
            <span id="mes">Febrero</span> del
            <span id="anyo">2019</span>
        </div>
    </div>
    
    <h3>en Le Bouquet Esthetiqué</h3>
    
    <style lang="less" scoped>
    @import url('https://fonts.googleapis.com/css?family=Parisienne&display=swap');

    * {
        color: #444;
        font-family: 'Parisienne', cursive;
        position: fixed;
    }

    h1 {
        top: 70px;
        left: 103px;
        font-size: 2rem;
    }

    h3 {
        top: 280px;
        left: 105px;
        font-size: 1.2rem;
    }

    #mensfecha {
        top: 250px;
        left: 110px;

        * {
            position: initial;
        }
    }
    p {
        top: 122px;
        left: 110px;
    }
    #descripcion {
        top: 160px;
        left: 110px;
        font-size: 1.4rem;
    }
</style>
<script>
    class Present {
        constructor($id) {
            
            this.el     = document.getElementById($id)
            this.style  = this.el.getElementsByTagName('style')[0]
            this.desc   = this.el.querySelector('#descripcion')
            this.day    = this.el.querySelector('#dia')
            this.month  = this.el.querySelector('#mes')
            this.year   = this.el.querySelector('#anyo')

        }
        description(arr = []) {
            if(arr != []){
                this.desc.innerHTML = ''
                for(let txt of arr){
                    this.desc.innerHTML += txt + '<br>';
                }
            }
            return this.desc.innerHTML
        }
        set date( date ) {
            let m = date.getMonth() + 1, 
                month = 1

            switch (m.toString()) {
                case '1' : month = 'Enero'; break;
                case '2' : month = 'Febrero'; break;
                case '3' : month = 'Marzo'; break;
                case '4' : month = 'Abril'; break;
                case '5' : month = 'Mayo'; break;
                case '6' : month = 'Junio'; break;
                case '7' : month = 'Julio'; break;
                case '8' : month = 'Agosto'; break;
                case '9' : month = 'Septiembre'; break;
                case '10' : month = 'Octubre'; break;
                case '11' : month = 'Noviembre'; break;
                case '12' : month = 'Diciembre'; break;
            }
            this.day.innerHTML = date.getDate()
            this.month.innerHTML = month
            this.year.innerHTML = date.getFullYear()
            
            return this.desc.innerHTML
        }
        clear() {
            this.day.innerHTML = ''
            this.month.innerHTML = ''
            this.year.innerHTML = ''
            this.desc.innerHTML = ''
        }
    }
    </script>
</component>