<component class="hidden" id="--id">
    <img src="/tpv/img/fondo_regalo.jpg" alt="Cheque regalo">
    <div id="contenedor_cheque_regalo">
        <h1>Cheque Regalo</h1>
        <h3>Disfute en Le Bouquet Esthetiqué</h3>
        <p>de los siguientes servicios:</p>
        <div id="descripcion"><!-- Tratamiento/s que se regala --></div>
        <div id="mensfecha">
            <p>Recuerde disfrutalos antes del:</p>
            <p>
                <div id="fecha">
                    <span id="dia"><!-- 13 --></span> de
                    <span id="mes"><!-- Febrero --></span> del
                    <span id="anyo"><!-- 2019 --></span>
                </div>
            </p>
        </div>
    </div>
    <style lang="less" scoped>
        @import url('https://fonts.googleapis.com/css?family=Parisienne&display=swap');

        #contenedor_cheque_regalo {
            color: #444;
            font-family: 'Parisienne',cursive;
            position: fixed;
            top: 69px;
            left: 85px;
            text-align: center;
            display: inherit;
            width: 252px;
            height: 270px;
        }
        h1 {
            font-size: 2rem;
        }
        h3 {
            font-size: 1.2rem;
            margin: 0;
        }
        p {
            margin:  0;
        }
        #descripcion {
            font-size: 1.4rem;
        }
        #mensfecha {
            width: 100%;
            position: absolute;
            bottom: 0; 
        }
    </style>
    <script>
        class Present {
            constructor(element) {
                this.el = element; 
                this.style = this.el.getElementsByTagName('style')[0];
                this.desc = this.el.querySelector('#descripcion');
                this.day = this.el.querySelector('#dia');
                this.month = this.el.querySelector('#mes');
                this.year = this.el.querySelector('#anyo');

            }
            description(arr = []) {
                if (arr != []) {
                    this.desc.innerHTML = ''
                    for (let txt of arr) {
                        this.desc.innerHTML += txt + '<br>';
                    }
                }
                return this.desc.innerHTML
            }
            set date(date) {
                let m = date.getMonth() + 1,
                    month = 1

                switch (m.toString()) {
                    case '1':
                        month = 'Enero';
                        break;
                    case '2':
                        month = 'Febrero';
                        break;
                    case '3':
                        month = 'Marzo';
                        break;
                    case '4':
                        month = 'Abril';
                        break;
                    case '5':
                        month = 'Mayo';
                        break;
                    case '6':
                        month = 'Junio';
                        break;
                    case '7':
                        month = 'Julio';
                        break;
                    case '8':
                        month = 'Agosto';
                        break;
                    case '9':
                        month = 'Septiembre';
                        break;
                    case '10':
                        month = 'Octubre';
                        break;
                    case '11':
                        month = 'Noviembre';
                        break;
                    case '12':
                        month = 'Diciembre';
                        break;
                }
                this.day.innerHTML = date.getDate()
                this.month.innerHTML = month
                this.year.innerHTML = date.getFullYear()

                return this.desc.innerHTML
            }
            clear() {
                this.description.innerHTML = ''
                this.day.innerHTML = ''
                this.month.innerHTML = ''
                this.year.innerHTML = ''
                this.desc.innerHTML = ''
            }
        }
    </script>
</component>