<section id="styles">
    <h1>Configuración de estilos</h1>
    <form id="styles_form">
        <m-select id="--id_f1" value="$$font1" label="Fuente principal" options="$$fonts" class="valid"/>
        <m-select id="--id_f2" value="$$font2" label="Fuente secundaria" options="$$fonts" class="valid"/>
        <m-input type="color" id="--id_c1" value="$$main_color" label="Color principal" />
        <m-input type="color" id="--id_c2" value="$$second_color" label="Color secundario" />
    </form>
    <script>
        app.styles = {
            buttons: [],
            name: 'styles',
            change: false,
            css_file: 'css/main.css',
            form: document.getElementById('styles_form'),
            font1: new MySelect("--id_f1"),
            font2: new MySelect("--id_f2"),
            color1: new MyInput("--id_c1"),
            color2: new MyInput("--id_c2"),
            load() {
                this.font1.change(_ => this.save());
                this.font2.change(_ => this.save());
                this.color1.change(_ => this.save());
                this.color2.change(_ => this.save());
            },
            exit() {
                
            },
            save() {
                app.post({
                    controller: this.name,
                    action: 'save',
                    data: {
                        'idioma': 'es',
                        'font1': this.font1.value(),
                        'font2': this.font2.value(),
                        'main-color': this.color1.value(),
                        'second-color': this.color2.value()
                    }
                }, (r, s) => {
                    if (s) {
                        let fileref = document.createElement("link");
                        fileref.setAttribute("rel", "stylesheet");
                        fileref.setAttribute("type", "text/css");
                        fileref.setAttribute("href", this.css_file);
                        document.getElementsByTagName("head")[0].appendChild(fileref);
                    }
                });
            }
        }
    </script>
</section>