<section id="unpaid">
    <m-table id="--id_table" columns="['ticket', 'fecha', 'nombre cliente', 'total']" class="hoverable"/>
    <script>
        app.unpaid = {
            buttons: [],
            table : new MyTable(--id_table), 
            load(){

            },
            open() {
                this.table.clear();
                // Petición de datos a la vista
                app.post({
                    controller: 'tickets',
                    action: 'unpaid',
                }, (d, r) => {
                    for( let i of d){
                        this.table.addLine(i.id, [i.id, i.fecha, i.nombre, i.total] );
                    }
                })
                // Cargamos los datos a la tabla
            }
        }
    </script>
</section>