<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TPV Online</title>

    <!-- css -->
    <link rel="stylesheet" type="text/css" media="screen" href="/css/main.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css"> -->

    <script
        src="https://code.jquery.com/jquery-3.4.0.min.js"
        integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
        crossorigin="anonymous">
    </script>
    <script src="./js/mods/tools.js"></script>   

</head>
<body>
    <main>
        <?php include_once $data->use('page') . '.phtml'?>
    </main>
    <script src="./js/main.js"></script>
</body>
</html>