<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TPV Online</title>

    <!-- FontIcons -->
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <!-- css -->
    <link rel="stylesheet" type="text/css" media="screen" href="../node_modules/js-datepicker/dist/datepicker.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/main.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css"> -->

    <script src="../node_modules/jquery/dist/jquery.min.js"></script>
    <script src="../node_modules/js-datepicker/dist/datepicker.min.js"></script> 
    <script src="./js/tools.min.js"></script> 
    <script src="./js/DataBase.min.js"></script> 
    <script src="./js/User.min.js"></script> 
    <script src="./js/Datepicker.min.js"></script>
</head>
<body>

    <?php include_once \VIEWS\LOGIN . $page . '.phtml'?>
    <script src="./js/main.min.js"></script>
    <script src="./js/app.min.js"></script>
   <!--  <script src="./js/Date.min.js"></script>  -->
</body>
</html>