<?php namespace app\views\components\controllers;?>
<section id="login" style="
    width: 420px; 
">
    <form>
        <fieldset  class="container">
            <legend>Login <?=$data->nombre?></legend>
            <?php 
                new InputText(['label'=>'Email del usuario', 'name'=>'email', 'required'=>false]);
                new InputPass(['label'=>'Contraseña', 'name'=>'pass', 'required'=>true])
            ?>
        </fieldset>
        <?php new ButtonSuccess; new ButtonCancel?>
    </form>
</section>
<script src="/js/login.min.js"></script>