<section id="login" style="
    width: 420px; 
">
    <form>
    <fieldset  class="container">
        <legend>Login <?= NOMBRE EMPRESA ?></legend>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="username">Username</label>
                <input type="text" class="collapse" id="Username" placeholder="Username"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Password</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
    </fieldset>
    <button class="primary collapse">Primary</button>
    </form>
</section>
<script src="/js/login.min.js"></script>