<?php namespace app\views\components\controllers;?>
<section id="loginnewuser" style="
    width: 420px; 
">
    <form controller="user" action="new">
        <h1><?=$Company->nombre()?></h1>
        <fieldset  class="container">
            <legend>Registro nuevo usuario</legend>
            <?php 
                new InputText(['label'=>'Nombre y apellidos', 'name'=>'nombre', 'class'=>'toverify', 'required'=>false]);

                $mail = new InputText(['label'=>'Email del usuario', 'name'=>'email', 'required'=>false]);
                new InputText(['label'=>'Repetir email', 'class'=>'verify', 'for'=>'input_'. $mail->id(), 'required'=>false]);

                $pass = new InputPass(['label'=>'Contraseña', 'name'=>'password', 'class'=>'toverify', 'required'=>true]);
                new InputPass(['label'=>'Repetir contraseña', 'class'=>'verify', 'for'=>'input_' . $pass->id(), 'required'=>true]);
            ?>
        </fieldset>
        <?php new ButtonSuccess; new ButtonCancel?>
    </form>
    <a href="login">Regresar a login</a>
</section>