<section id="newcompany" style="
    width: 420px; 
">
    <form>
    <fieldset  class="container">
        <legend>Registro nueva empresa</legend>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="username">Nombre Empresa</label>
                <input type="text" class="collapse" id="Username" placeholder="Username"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="username">NIF</label>
                <input type="text" class="collapse" id="Username" placeholder="Username"/>
            </div>
        </div>
    </fieldset>
    <br>
    <fieldset  class="container">
        <legend>Administrador empresa</legend>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Nombre</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Apellidos</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Fecha nacimiento</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Password</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>

    </fieldset>
    <br>
    <fieldset  class="container">
        <legend>Direccion empresa</legend>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Calle</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Numero</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Piso</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Escalera</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Población</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">CP</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Provincia</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <label for="password">Pais</label>
                <input type="password" class="collapse" id="password" placeholder="Password"/>
            </div>
        </div>
    </fieldset>
    <?php myrequire('btn-aceptar')?>
    
    <button type="button" class="secondary collapse">Cancelar</button>
    </form>
</section>
<script src="/js/login.min.js"></script>