<?php namespace app\views\components\controllers;?>
<section id="newcompany" style="
    width: 420px; position=relative
">
    <form controller="company" action="new" autocomplete="off">
        <fieldset  class="container">
            <legend>Nueva aplicación</legend>
            <?php             
            new InputText(['name'=>'nombre_empresa', 'label'=>'Nombre de la empresa', 'required'=>true]);
            new InputText(['name'=>'nif', 'label'=>'NIF', 'pattern'=> '(([X-Z]{1})([-]?)(\d{7})([-]?)([A-Z]{1}))|((\d{8})([-]?)([A-Z]{1}))' ,'required'=>true]);
            new Select(['label'=>'Seleccione su sector', 'name'=>'sector', 'required' => true,
                'options' => [
                    1 => 'Peluqueria',
                    2 => 'Estética',
                    3 => 'Masaje',
                    4 => 'Otros'
                    ]]);
            new InputText(['name'=>'nombre_usuario', 'label' => 'Nombre del administrador', 'required' => true]);
            new InputText(['name'=>'apellidos', 'label'=>'Apellidos del administrador', 'required'=>true]);
            new InputText(['name'=>'email', 'label'=>'Introduzca su email', 'required'=>true]);
            new InputText(['label'=>'Repita el email', 'required'=>true]);
            new InputPass(['name'=>'password', 'label'=>'Introduzca una contraseña', 'required'=>true]);
            new InputPass(['label'=>'Repita la contraseña', 'required'=>true]);
            ?>
        </fieldset>
        <?php new ButtonSuccess?>
        <a href="main">Ir al inicio</a>
    </form>
</section>
<!-- <script src="/js/newc.min.js"></script> -->